package ch.ergon.adam.integrationtest.oracle;

import ch.ergon.adam.core.db.schema.*;
import ch.ergon.adam.integrationtest.AbstractDbTestBase;
import ch.ergon.adam.integrationtest.DummySink;
import org.junit.jupiter.api.Test;

import static ch.ergon.adam.core.db.schema.DataType.DECIMAL_INTEGER;
import static ch.ergon.adam.core.db.schema.DataType.NUMERIC;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;

public class OracleCreateTableTest extends AbstractDbTestBase {

    public OracleCreateTableTest() {
        super(new OracleTestDbUrlProvider());
    }

    private static final String YML = "---\n" +
        "name: \"TEST_TABLE\"\n" +
        "fields:\n" +
        "- name: \"ID\"\n" +
        "  dataType: \"DECIMAL_INTEGER\"\n" +
        "  precision: 38\n" +
        "  sequence: true\n" +
        "- name: \"COL1\"\n" +
        "  dataType: \"DECIMAL_INTEGER\"\n" +
        "  precision: 38\n" +
        "- name: \"COL2\"\n" +
        "  dataType: \"NUMERIC\"\n" +
        "  defaultValue: \"10\"\n" +
        "  nullable: true\n" +
        "  precision: 10\n" +
        "  scale: 2\n" +
        "- name: \"COL3\"\n" +
        "  dataType: \"CLOB\"\n" +
        "  nullable: true\n" +
        "- name: \"COL4\"\n" +
        "  dataType: \"VARCHAR\"\n" +
        "  length: 10\n" +
        "indexes:\n" +
        "- name: \"TEST_TABLE_COL1_KEY\"\n" +
        "  fields:\n" +
        "  - \"COL1\"\n" +
        "  unique: true\n" +
        "- name: \"TEST_TABLE_PKEY\"\n" +
        "  fields:\n" +
        "  - \"ID\"\n" +
        "  primary: true\n" +
        "  unique: true\n" +
        "--- []\n" +
        "--- []\n";

    private static final String CREATE_TABLE_SQL =
        "create table test_table (" +
            "id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY, " +
            "col1 INTEGER not null, " +
            "col2 NUMBER(10,2) DEFAULT 10 null, " +
            "col3 CLOB null, " +
            "col4 VARCHAR2(10) not null, " +
            "CONSTRAINT test_table_pkey PRIMARY KEY (id), " +
            "CONSTRAINT test_table_col1_key UNIQUE (col1)" +
            ")";

    private void verifySchema(Schema schema) {
        assertNotNull(schema);
        assertThat(schema.getTables().size(), is(1));
        assertTrue(schema.getViews().isEmpty());
        assertTrue(schema.getEnums().isEmpty());

        Table table = schema.getTable("TEST_TABLE");
        assertNotNull(table);
        assertThat(table.getFields().size(), is(5));

        Field field = table.getField("ID");
        assertNotNull(field);
        assertThat(field.getIndex(), is(0));
        assertFalse(field.isNullable());
        assertFalse(field.isArray());
        assertNull(field.getLength());
        assertThat(field.getPrecision(), is(38));
        assertNull(field.getScale());
        assertTrue(field.isSequence());
        assertNull(field.getDefaultValue());
        assertNull(field.getDbEnum());
        assertThat(field.getDataType(), is(DECIMAL_INTEGER));

        field = table.getField("COL1");
        assertNotNull(field);
        assertThat(field.getIndex(), is(1));
        assertFalse(field.isNullable());
        assertFalse(field.isArray());
        assertNull(field.getLength());
        assertThat(field.getPrecision(), is(38));
        assertNull(field.getScale());
        assertFalse(field.isSequence());
        assertNull(field.getDefaultValue());
        assertNull(field.getDbEnum());
        assertThat(field.getDataType(), is(DECIMAL_INTEGER));

        field = table.getField("COL2");
        assertNotNull(field);
        assertThat(field.getIndex(), is(2));
        assertTrue(field.isNullable());
        assertFalse(field.isArray());
        assertNull(field.getLength());
        assertThat(field.getPrecision(), is(10));
        assertThat(field.getScale(), is(2));
        assertFalse(field.isSequence());
        assertThat(field.getDefaultValue(), is("10"));
        assertNull(field.getDbEnum());
        assertThat(field.getDataType(), is(NUMERIC));

        field = table.getField("COL3");
        assertNotNull(field);
        assertThat(field.getIndex(), is(3));
        assertTrue(field.isNullable());
        assertFalse(field.isArray());
        assertNull(field.getLength());
        assertNull(field.getPrecision());
        assertNull(field.getScale());
        assertFalse(field.isSequence());
        assertNull(field.getDefaultValue());
        assertNull(field.getDbEnum());
        assertThat(field.getDataType(), is(DataType.CLOB));

        field = table.getField("COL4");
        assertNotNull(field);
        assertThat(field.getIndex(), is(4));
        assertFalse(field.isNullable());
        assertFalse(field.isArray());
        assertThat(field.getLength(), is(10));
        assertNull(field.getPrecision());
        assertNull(field.getScale());
        assertFalse(field.isSequence());
        assertNull(field.getDefaultValue());
        assertNull(field.getDbEnum());
        assertThat(field.getDataType(), is(DataType.VARCHAR));

        Index index = table.getIndex("TEST_TABLE_PKEY");
        assertNotNull(index);
        assertTrue(index.isPrimary());
        assertTrue(index.isUnique());
        assertThat(index.getFields().size(), is(1));
        assertThat(index.getFields().get(0).getName(), is("ID"));

        index = table.getIndex("TEST_TABLE_COL1_KEY");
        assertNotNull(index);
        assertFalse(index.isPrimary());
        assertTrue(index.isUnique());
        assertThat(index.getFields().size(), is(1));
        assertThat(index.getFields().get(0).getName(), is("COL1"));
    }

    @Test
    public void testCreateTable() throws Exception {
        getSourceDbConnection().createStatement().execute(CREATE_TABLE_SQL);
        sourceToTarget();
        DummySink dummySink = targetToDummy();
        Schema schema = dummySink.getTargetSchema();
        verifySchema(schema);
    }

    @Test
    public void testCreateTableToYml() throws Exception {
        getSourceDbConnection().createStatement().execute(CREATE_TABLE_SQL);
        sourceToTarget();
        String yml = targetToYml();
        assertEquals(YML, yml);
    }

}
