plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '2.2.1'
}

group = 'ch.ergon.adam'
description = 'The ADAM Gradle Plugin'

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation gradleApi()
    implementation project(':core')
    implementation 'org.jooq:jooq-codegen:3.19.39'
}

apply from: "${rootProject.projectDir}/common.gradle"

gradlePlugin {
    website = 'https://github.com/ergon/adam/'
    vcsUrl = 'https://github.com/ergon/adam.git'
    plugins {
        adamPlugin {
            id = 'ch.ergon.adam'
            displayName = 'ADAM Plugin'
            description = 'Advanced DAtabase Migration to migrate database schema'
            implementationClass = 'ch.ergon.adam.gradleplugin.AdamPlugin'
            tags = ['database', 'schema', 'migration', 'postgresql', 'sqlite', 'jooq', 'ergon']
        }
    }
}

publishing {
    repositories {
        maven {
            name = "localPluginRepository"
            url = uri("/tmp/adam/local-gradle-plugin-repository")
        }
    }
}

