name: Build and Test

on: [ push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk

    steps:
      - name: Install dependencies
        run: apt update && apt install git -y
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: ./gradlew -S -i assemble -PjooqProUser=${{ secrets.JOOQ_PRO_USER }} -PjooqProPassword=${{ secrets.JOOQ_PRO_PASSWORD }}
      - name: Test
        run: ./gradlew -S -i test -PjooqProUser=${{ secrets.JOOQ_PRO_USER }} -PjooqProPassword=${{ secrets.JOOQ_PRO_PASSWORD }}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./**/build/test-results/**/*.xml

