name: Publish to Maven Central

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Prepare GPG key
        run: mkdir ~/.jreleaser && echo '${{secrets.JRELEASER_CONFIG_YML_BASE64}}' | base64 -d > ~/.jreleaser/config.yml

      - name: Upload
        run: ./gradlew -S -i publish jreleaserDeploy -PjooqProUser=${{ secrets.JOOQ_PRO_USER }} -PjooqProPassword=${{ secrets.JOOQ_PRO_PASSWORD }}

      - name: Cleanup
        if: always()
        run: rm build/adam_signing_key.gpg
